name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest # or windows-2022 or windows-2019

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 4.7.2

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish
        run: dotnet publish --configuration Release --output publish

  artifacts:
    runs-on: windows-latest # or windows-2022 or windows-2019

    needs: build

    steps:
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-artifacts
          path: publish
